In [7]:
import numpy as np
data = np.genfromtxt("odd_numbers.txt", invalid_raise = False)
print(data)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]
 [21. 23. 25. 27. 29.]
 [31. 33. 35. 37. 39.]]


C:\Users\Vaibhav\AppData\Local\Temp\ipykernel_16280\3006305123.py:2: ConversionWarning: Some errors were detected !
    Line #5 (got 4 columns instead of 5)
  data = np.genfromtxt("odd_numbers.txt", invalid_raise = False)


In [6]:
data = np.genfromtxt("odd_numbers_2.csv", delimiter=",",filling_values = 0)
print(data)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]
 [21. 23. 25. 27. 29.]
 [31. 33. 35. 37. 39.]
 [43. 45. 47. 49.  0.]]
